version: '3'

services:
  app:
    image: docker-nextjs-dev
    build: 
      context: ./frontend
      dockerfile: ../docker/Dockerfile-frontend
    container_name: klinicos_front
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    ports:
      - 3000:3000